---
abstract: 'determine Czech Republic bank holidays'
author:
  - 'Nathan Cutler <presnypreklad@gmail.com>'
build_requires:
  Exporter: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Holidays-CZ
no_index:
  directory:
    - t
    - inc
requires:
  Date::Easter: 0
  Date::Simple: 0
  Exporter: 0
  perl: 5.01
version: 0.06
